### PR TITLE
support multi prompts

### PR DESCRIPTION
**Pull request by pythias**
p.prompt is list|str

### CODE REVIEW

**Comment by ototadana** [comment]
@pythias 
Thanks for sending the PR!

I did not know that p.prompt could be a list. Thanks for letting me know. If you don't mind, could you please tell me the specific operation of the case where p.prompt becomes a list? Because I would like to see what problems the existing implementation causes and how it can be improved with this PR.

**Comment by pythias** [comment]
@ototadana When I want to generate multiple styles in one api request, like the script '/stable-diffusion-webui/scripts/prompt_matrix.py'

**Comment by ototadana** [comment]
@pythias 
Thank you for your reply.

I apologize for my lack of understanding. Am I correct in understanding that this is a case of API calls only, not UI operations? And that you want to apply different prompts to each of the generated images?

If this understanding is correct, could you give me an example of a request for an API call, if you don't mind? I am quite interested in such a use case and would like to study it. (If this understanding is incorrect and could happen with UI operations, I would like to know the actual operation.)

Thank you.

**Comment by pythias** [comment]
@ototadana  
Thank you for your reply.

You can call like this params
```bash
curl -X POST -H "Content-Type: application/json" 'https://127.0.0.1:7860/sdapi/v1/txt2img' -d '{"prompt":"winter|spring","script_name":"prompt matrix","script_args":[true,true,"positive","comma",10]}'
```

However, since the number of images returned by the face editor is twice the original number, it caused an error  (`  File "./stable-diffusion-webui/modules/images.py", line 179, in draw_grid_annotations
    assert cols == len(hor_texts), f'bad number of horizontal texts: {len(hor_texts)}; must be {cols}'`) when SD was drawing the grid. I remember that in a certain version, you provided the option to return only the final result.

谢谢你

**Comment by pythias** [comment]
@ototadana  

In the extension I wrote, this is how I used it. I wrapped the original SD interface. When there are multiple style requests in the interface, I would modify the 'prompt' attribute in the StableDiffusionProcessing object.

```python
def apply_multi_process(p: StableDiffusionProcessing):
    prompts = to_multi_prompts(p.prompt)
    if len(prompts) == 1:
        return
    
    processing.fix_seed(p)
    same_seed = get_extra_value(p, 'same-seed', False)

    p.prompt = prompts
    p.batch_size = 1
    p.n_iter = len(p.prompt)
    p.seed = [p.seed + (0 if same_seed else i) for i in range(len(p.prompt))]
```

https://github.com/pythias/sd-character-extension/blob/3475674df521e116de55d16c33b7432ac65c59a4/character/models.py#L171

**Comment by ototadana** [comment]
@pythias 
Thank you very much for your detailed explanation. You have given me a better understanding of the issues.

What do you think of the following modification to the [proc_images](https://github.com/ototadana/sd-face-editor/blob/bc82e06af204df0e51b46b729c7a7b7ee5a73a31/scripts/use_cases/image_processor.py#L55) function?

```python
        if type(p.prompt) == list:
            p.prompt = p.prompt[i]
        proc = self.proc_image(p, option, image)
```
If there is no problem with such a modification, I would be willing to implement a modification based on this on my end after merging this PR. (I'm thinking of perhaps a slightly pessimistic implementation that would work even if `len(res.images)` and `len(p.prompt)` do not match, [similar to the treatment for `p.seed` and `p.subseed`](https://github.com/ototadana/sd-face-editor/blob/main/scripts/use_cases/image_processor.py#L49-L54).)

> However, since the number of images returned by the face editor is twice the original number, it caused an error

Thank you. This is another issue. We will be adding new options to address this.

**Comment by pythias** [comment]
@ototadana  
Your implement is better, thank you.

**Comment by ototadana** [comment]
@pythias 
Thank you very much.

**Pull request merged**
